THEME_NAME="my-nord-grub"
BG_IMAGE="assets/bg.png"
FONT_FILE="fonts/MesloLGS-NF-Bold.ttf"

FONT_TITLE_SIZE=60
FONT_ITEM_SIZE=16
FONT_TIMEOUT_SIZE=32
FONT_TERMINAL_SIZE=16

MENU_LEFT="-32%"
MENU_WIDTH="45%"
MENU_TOP="65%"
MENU_HEIGHT=500

# Nord palette
ITEM_COLOR="#D8DEE9"
SELECTED_ITEM_COLOR="#88C0D0"
TIMEOUT_COLOR="#D8DEE9"

SELECT_PIXMAP="assets/select_c.png"
SELECT_PIXMAP_PATTERN="select_*.png"
