THEME_NAME="my-nord-grub"
BG_IMAGE="assets/bg.png"
FONT_TITLE_PF2="fonts/meslo_60_bold.pf2"
FONT_ITEM_PF2="fonts/meslo_16_bold.pf2"
FONT_TIMEOUT_PF2="fonts/meslo_32_bold.pf2"
FONT_TERMINAL_PF2="fonts/meslo_16_bold.pf2"

MENU_LEFT="-32%"
MENU_WIDTH="45%"
MENU_TOP="65%"
MENU_HEIGHT=500

# Nord palette
ITEM_COLOR="#D8DEE9"
SELECTED_ITEM_COLOR="#88C0D0"
TIMEOUT_COLOR="#D8DEE9"

SELECT_PIXMAP="assets/select_c.png"
SELECT_PIXMAP_PATTERN="select_*.png"
